site_name: rote-satio

nav:
  - Home: index.md
  - Installation: installation.md
  - API: api/module.md
  - Examples:
      - Segmentation:
          - Custom: examples/kmeans.ipynb
          - Pretrained: examples/segmentation.ipynb

theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "light-blue"

plugins: { mkdocstrings, glightbox, mkdocs-jupyter }


markdown_extensions:
  - attr_list
  - md_in_html